### PR TITLE
Fix linter issues

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

---

**Related issue :**

### CODE REVIEW

**Comment by enolfc** [comment]
Still missing wrong links in one file. See https://github.com/EGI-Foundation/documentation/pull/172/checks?check_run_id=1604825797#step:4:35

no idea on how to make this work 🤷

**Comment by gwarf** [comment]
> Still missing wrong links in one file. See https://github.com/EGI-Foundation/documentation/pull/172/checks?check_run_id=1604825797#step:4:35
> 
> no idea on how to make this work 🤷

So I feel like the markdown link checker may be interpreting the link incorrectly, as it's not proper markdown but an hugo shortcode.
Mabye we don't have much other solutions than adding an exception for this content. Or play with the [replacement option](https://github.com/tcort/markdown-link-check#config-file-format) to drop the quote, but not sure it's a good/clean idea.

**Comment by enolfc** [comment]
> > Still missing wrong links in one file. See https://github.com/EGI-Foundation/documentation/pull/172/checks?check_run_id=1604825797#step:4:35
> > no idea on how to make this work 🤷
> 
> So I feel like the markdown link checker may be interpreting the link incorrectly, as it's not proper markdown but an hugo shortcode.
> Mabye we don't have much other solutions than adding an exception for this content. Or play with the [replacement option](https://github.com/tcort/markdown-link-check#config-file-format) to drop the quote, but not sure it's a good/clean idea.

What I don't understand is why the egi.eu and docs.egi.eu links fail but not the twitter one. I can add an exception for exactly those two links with `&quote;`

**Review by gwarf — APPROVED** [review]
LGTM, thanks!

**Review by andrea-manzi — APPROVED** [review]
thanks  a lot!

**Pull request merged**
