### PR TITLE
[Check-in] Add description for SSH Public Key attribute

### PR DESCRIPTION
**Pull request by nikosev**
# Summary

This PR adds the description of the new SSH Public Key attribute in Service Provider guide of Check-in

### CODE REVIEW

**Comment by gwarf** [comment]
So it looks like openid.net is at least temporarily down and as it's not part of this PR I think we can ignore the error.

**Review by gwarf — APPROVED** [review]
Thanks, LGTM!

Let's merge this once it will have been deployed in production, so please let us know when it's done.

**Comment by nikosev** [comment]
Hello @gwarf !
The support for SSH Public Key attribute has been deployed to production.
Could you please proceed with the merge of this PR?

**Comment by gwarf** [comment]
And in the meantime openid pages came back online, perfect, thanks a lot!

**Pull request merged**
