### PR TITLE
updated gitignore

### PR DESCRIPTION
**Pull request by yihyang**
# Summary

Updated `.gitignore` with reference to: https://github.com/EGI-Foundation/documentation/issues/87

---

**Related issue :**
https://github.com/EGI-Foundation/documentation/issues/87

### CODE REVIEW

**Comment by gwarf** [comment]
Hi @yihyang, thanks for the PR!
I would prefer to only add entries that are meaningful for this project, not adding lots of things that could exist but that won't be found in this repo, can you drop all the things that are not generated by hugo/used there?

**Review by gwarf — CHANGES_REQUESTED** [review]
See comment: please drop all the things that are not generated by hugo/used/meaningful for this specific repo.

**Comment by yihyang** [comment]
Hi @gwarf , I have updated the changes. Please have a look again, thanks!

**Comment by gwarf** [comment]
Hi @yihyang,
So I feel like the first `.DS_Store` entry should be enough and covering also the one located deeper in the hierarchy.
Could you also please delete the existing `.DS_Store` files that have already been committed to the repository? With this all would be clean, thanks!

**Comment by yihyang** [comment]
Hi @gwarf , I have removed the existing DS_Store files in https://github.com/EGI-Foundation/documentation/pull/113/commits/b5162837f32f888f543b40bf804261d55b6e26b6

**Review by gwarf — APPROVED** [review]
LGTM, thanks a lot!
Enjoy the nice hacktoberfest T-Shirt ;)

**Comment by yihyang** [comment]
Thanks @gwarf !

**Pull request merged**
